# Baseline:
## Generate baseline from XSD
- soya.framework.tools.xmlbeans.XmlSchemaBaseLoader:
    schema: CMM/BOD/GetGroceryOrder.xsd

# Annotations:
## Application Definition:
- soya.framework.tools.xmlbeans.ApplicationAnnotator:
    uri: BusinessObjects/GroceryOrder/application.json

## Apply basic annotation from xlsx mapping sheet:
- soya.framework.tools.xmlbeans.XlsxMappingAnnotator:
    sourceFiles: # load source json from files
      - BusinessObjects/GroceryOrder/requirement/erums.json
      - BusinessObjects/GroceryOrder/requirement/echo.json
      - BusinessObjects/GroceryOrder/requirement/wysiwyg.json
      - BusinessObjects/GroceryOrder/requirement/oms.json
    mappingFile: BusinessObjects/GroceryOrder/requirement/GroceryOrder_ERUMS_to_Canonical_Mapping_v1.6.2.xlsx
    mappingSheet: "Mapping_ERUMS_OMS to Canonical"
    excludes: # mappings defined but not in this version
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/Address/PhoneNbr

## Apply node attribute changes:
- soya.framework.tools.xmlbeans.XmlSchemaNodeAnnotator:
    nodes:
      GetGroceryOrder/DocumentData/Document:
        namespaceURI: http://collab.safeway.com/it/architecture/info/default.aspx
      GetGroceryOrder/DocumentData/DocumentAction:
        namespaceURI: http://collab.safeway.com/it/architecture/info/default.aspx
      GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem:
        cardinality: 0-n

## Fix unknown mappings: target paths, source paths and mapping rules...
- soya.framework.tools.xmlbeans.UnknownMappingFixAnnotator:
    fixes:
      ### unknown target paths:
      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/DocumentData/Document/SystemEnvironmentCd
        fix: GetGroceryOrder/DocumentData/Document/@SystemEnvironmentCd

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/PhoneFaxContact/TypeCode
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/PhoneFaxContact/@TypeCode

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/DigitalContact/EmailStatuses/typeCode
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/DigitalContact/EmailStatuses/@typeCode

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/EditCutoffDttm
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/EditCutoffDtTm

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/DeliverytimeZoneCd
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/DeliveryTimeZoneCd

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/CustomerService/PhoneFaxContact/TypeCode
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/CustomerService/PhoneFaxContact/@TypeCode

      ### unknown source path:
      - unknownType: UNKNOWN_SOURCE_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/Address/PostalZoneCd
        fix: customer/address[*]/zipCode

## Generate assignments:
- soya.framework.tools.xmlbeans.MappingAnnotator:
    globalVariables:
      - name: VERSION_ID
        type: CHARACTER
        defaultValue: "'1.6.2.073'"
      - name: SYSTEM_ENVIRONMENT_CODE
        type: CHARACTER
        defaultValue: "'PROD'"

    mappingFile: BusinessObjects/GroceryOrder/xpath-assignment.properties

# Renderers:
## Print XML construct tree as Avro:
- soya.framework.tools.xmlbeans.AvroSchemaRenderer:
    name: AvroSchema

## Print node tree in json, indexed by xpath:
- soya.framework.tools.xmlbeans.XmlSchemaTreeRenderer:
    name: XmlSchemaTree

## Print Unknown mappings:
- soya.framework.tools.xmlbeans.UnknownMappingsRenderer:
    name: UnknownTargets
    types:
      - UNKNOWN_TARGET_PATH

- soya.framework.tools.xmlbeans.UnknownMappingsRenderer:
    name: UnknownSources
    types:
      - UNKNOWN_SOURCE_PATH

- soya.framework.tools.xmlbeans.UnknownMappingsRenderer:
    name: UnknownOthers
    types:
      - UNKNOWN_MAPPING_RULE
      - ILLEGAL_SOURCE_PATH

## Print XPath Mappings:
- soya.framework.tools.xmlbeans.XPathMappingsRenderer:
    name: XPathMappings
    printUnmapped: true

## Analyze Loops:
- soya.framework.tools.xmlbeans.LoopAnalyzeRenderer:
    name: LoopAnalyzer

## Print Loops:
- soya.framework.tools.xmlbeans.XPathAutoAnnotateRenderer:
    name: XPathAutoAnnotate

## Print XPath Assignments:
- soya.framework.tools.xmlbeans.XPathAssignmentsRenderer:
    name: XPathAssignments
    printUnmapped: false

## Print Sample XML:
- soya.framework.tools.xmlbeans.SampleXmlRenderer:
    name: SampleXml


## Print XML construct tree:
- soya.framework.tools.xmlbeans.XmlConstructTreeRenderer:
    name: XmlConstructTree

## Print ESQL
- soya.framework.tools.xmlbeans.XmlConstructEsqlRenderer:
    name: ESQL
    brokerSchema: com.abs.osms.deliveryslot
    moduleName: ESED_DELIVERYSLOT_OSMS_CMM_Compute
    inputRootVariable: _inputRootNode
    inputRootReference: InputRoot.JSON.Data

## Print transformation output xml:
- soya.framework.tools.xmlbeans.XmlMessageRenderer:
    inputMessageFile: BusinessObjects/GroceryOrder/requirement/input.json

## Print Avro Schema
- soya.framework.tools.xmlbeans.AvroSchemaRenderer:
    name: AvroSchema

## Print deployment artifacts:
- soya.framework.tools.xmlbeans.OverridePropertiesRenderer:
    name: OverrideBaseline
    template: Templates/override.pr.mustache
    excludes:
      - com.abs.cmnflows.WebServiceResponseValidator
      - com.abs.cmnflows.Audit_Middle
      - com.abs.cmnflows.RetryValidate_Exception

- soya.framework.tools.xmlbeans.OverridePropertiesRenderer:
    name: OverrideDev
    template: Templates/override.dv.mustache
    excludes:
      - com.abs.cmnflows.WebServiceResponseValidator
      - com.abs.cmnflows.Audit_Middle
      - com.abs.cmnflows.RetryValidate_Exception

- soya.framework.tools.xmlbeans.OverridePropertiesRenderer:
    name: OverrideQA
    template: Templates/override.qa.mustache
    excludes:
      - com.abs.cmnflows.WebServiceResponseValidator
      - com.abs.cmnflows.Audit_Middle
      - com.abs.cmnflows.RetryValidate_Exception

- soya.framework.tools.xmlbeans.OverridePropertiesRenderer:
    name: IIBConsole
    template: Templates/iib.mustache
    includeEmpty: true